### ISSUE TITLE
contains() method for embeds & messages

### ISSUE THREAD

**Issue by Pchola99** [DWolf-19/JDA-Extra#137]
Currently, to understand if a message contains a string, it is enough to call contains() on the message, but what if the message is not just a text message, but an embed? What if there are several embed? You have to go through each one, check all fields in each one, including footer, description, title, before you can figure out if it contains a certain string. 
  I suggest making a static method like `JDAEUtils.contains(MessageReceivedEvent message, String containsFiled);` that takes a message and a substring. It checks if the message contains the substring by checking each embed field (if present), and just the message itself if there is no embed, the internal implementation could be something like this:
```java
    public static boolean contains(MessageReceivedEvent message, String containsFiled) {
        if (!message.getMessage().getEmbeds().isEmpty()) {
            List<MessageEmbed> embeds = message.getMessage().getEmbeds();

            for (MessageEmbed embed : embeds) {
                String description = embed.getDescription();
                String title = embed.getTitle();

                if ((title != null && title.contains(containsFiled)) || (description != null && description.contains(containsFiled))) {
                    return true;
                }

                for (int j = 0; j < embed.getFields().size(); j++) {
                    if (embed.getFields().get(j).getValue().contains(containsFiled)) {
                        return true;
                    }
                }
            }
        } else {
            return message.getMessage().getContentDisplay().contains(containsFiled);
        }
        return false;
    }
```

**Comment by DWolf-19** [comment]
Thank you for feedback! I will review this change and think about utilities for working with text.

**Comment by DWolf-19** [comment]
Moved to https://gitlab.com/DWolf_19/JDA-Extra/-/issues/137.
